id: I22DC4D74
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:11:12+00:00'
last_modified: '2022-06-08T09:35:15.652532+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ294451
  title: དཔལ་ཆེན་རིགས་བཞིའི་ལས་བྱང་རྒྱས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C76B:
      image_group_id: I4CZ294575
      title: ''
      total_pages: 190
      order: 1
      base_file: C76B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
