id: I22DC4D74
legacy_id: P006912
ocr_import_info:
  bdrc_scan_id: W4CZ294451
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T15:10:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T18:28:40.850996+00:00'
last_modified: 2022-09-04 02:28:47.605587
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ294451
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ294451
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་ཆེན་རིགས་བཞིའི་ལས་བྱང་རྒྱས་པ།
  author: མཁྱེན་བརྩེའི་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.663440990053992
  ocr_word_median_confidence_index: 0.699999988079071
quality: null
bases:
  I4CZ294575:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ294575
      total_pages: 190
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ294575.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.663440990053992
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
