id: P006912
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:30:18.896384
source_metadata:
  id: bdr:W4CZ294451
  title: དཔལ་ཆེན་རིགས་བཞིའི་ལས་བྱང་རྒྱས་པ།
  author: ''
  volumes:
    f4a23d8d7ce84bfe81c9a3317d809b4e:
      image_group_id: I4CZ294575
      title: ''
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
